blog/urls.py
from django.conf.urls import url
from blog.views import * # 이렇게 수정하면 아래와 같이 views.~ 형식에서 views. 부분을 빼야 함
                         # bookmark.urls에서는 from . import views로 했으므로 views.~ 형식으로 사용해야 함
                         # * 표시는 모든 멤버를 일괄 지정함
urlpatterns = [

  # Example: /
  url(r'^$', PostLV.as_view(), name='index'),

  # Example: /post/ (same as /)
  url(r'^post/$', PostLV.as_view(), name='post_list'),

  # Example: /post/django-example/
  url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

  # Example: /archive/
  url(r'^archive/$', PostAV.as_view(), name='post_archive'),

  # Example: /2012/
  url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

  # # Example: /2012/nov/  <== 영어식 날짜 표기 형태로
  url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),
  # # Example: /2012/11/
  # url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostMAV.as_view(), name='post_month_archive'),

  # # Example: /2012/nov/10/  <== 영어식 날짜 표기 형태로
  url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
  # # Example: /2012/11/10/
  # url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

  # Example: /today/
  url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
]
# 위에서 지정한 name 항목을 템플릿에서 사용할 때에는 이름공간을 포함하여,
# blog:index, blog:post_list, blog:post_detail, blog:post_archive, ... 로 명시해야 함

mysite/urls.py
# from django.conf.urls import url, include
# from django.contrib import admin
#
# from bookmark.views import BookmarkLV, BookmarkDV
#
# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     url(r'', include('bookmark.urls')),
# ]


# 장고 내장 함수 include() 및 url() 임포트
from django.conf.urls import include, url
from django.contrib import admin

# 이 부분은 bookmark.urls 부분으로 옮겼음
# from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
    # admin.site.urls를 include(admin.site.urls)로 변경했으나 사실 동일한 효과를 발휘
    # 다른 앱에서 정의된 url 설정을 재활용할 때 include() 함수를 써야 하지만,
    # 예외적으로 admin.site.urls에 대해서는 include() 함수를 생략해도 무방함
    url(r'^admin/', include(admin.site.urls)),

    # 아래 두 url 패턴에서 뒷 부분에 패턴의 끝을 표시하는 '$' 문자가 없음!!!

    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    # bookmark.urls를 적용하고, 이름공간을 'bookmark'로 지정
    url(r'^blog/', include('blog.urls', namespace='blog')),
    # blog.urls를 적용하고, 이름공간을 'blog'로 지정
]

blog/models.py
# 문자열 처리 방식이 상이한 파이썬 버전 2 및 3의 호환성을 위한 임포트
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
# url 패턴을 만들어주는 장고 내장 함수 reverse()를 위한 임포트
from django.core.urlresolvers import reverse

# Create your models here.

@python_2_unicode_compatible
class Post(models.Model):
    # 아래에서 관리자 화면의 레이블과 도움말은 모두 한글로 수정하였음(교과서에서는 대문자 영문이었음)
    # 한 줄로 입력되는 CharField
    title = models.CharField('제목', max_length=50)
    slug = models.SlugField('슬러그',  # 기본 길이 50, 인덱스가 기본 생성됨,
                                       # 제목에서 주요 단어를 하으픈으로 연결하여 생성
                            unique=True,  # unique 설정, 기본키 대용으로 사용 가능
                            allow_unicode=True,  # 한글 입력 가능하도록
                            help_text='제목에 대한 한 단어의 별명.')
    description = models.CharField('설명',
                                   max_length=100,
                                   blank=True,  # 블랭크 허용
                                   help_text='간략한 설명 문구.')
    content = models.TextField('내용')  # TextField이므로 여러 줄 입력 가능함
    create_date = models.DateTimeField('최초 생성 일시',
                                       auto_now_add=True)  # 최초 생성 일시를 자동 저장하도록
    modify_date = models.DateTimeField('최종 수정 일시',
                                       auto_now=True)  # 최종 수정 일시를 자동 저장하도록

    class Meta:  # 필드 속성 외에 필요한 파라미터를 Meta 내부 클래스로 정의
        verbose_name = '기사'              # 'post'
        verbose_name_plural = '기사 모음'  # 'posts'
        db_table  = 'my_posts'           # DB에 저장할 테이블 이름을 my_posts'라고 지정
                                         # 기본값(앱이름_모델클래스이름)은 'blog_post'
        ordering  = ('-modify_date',)  # 최종 수정 일시의 내림차순 정렬

    def __str__(self):
        return self.title  # 객체를 출력할 때 제목만 출력

    def get_absolute_url(self): # 이 메소드가 정의된 객체를 지칭하는 URL을 반환
        # 아래에서 'blog:post_detail'는 blog 앱 이름공간의 post_detail이란 의미
        # # Example: /post/django-example/
        # url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
        return reverse('blog:post_detail', args=(self.slug,))
    def get_previous_post(self):  # 3.2.5 항에서 템플릿 작성할 때 사용
        return self.get_previous_by_modify_date()

    def get_next_post(self):  # 3.2.5 항에서 템플릿 작성할 때 사용
        return self.get_next_by_modify_date()

blog/views.py
# 뷰 작성에 필요한 클래스형 제넥릭 뷰 임포트
from django.views.generic import ListView, DetailView
# 뷰 작성에 필요한 날짜 제네릭 뷰 임포트
from django.views.generic.dates import ArchiveIndexView, \
    YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView
# blog.models.Post 클래스 임포트
from blog.models import Post

# ListView를 상속받아서 PostLV 작성
class PostLV(ListView) :
    model = Post
    # 기본값 'blog/post_list.html' 대신 지정 (3.1.4 URL 설계 항 참고)
    template_name = 'blog/post_all.html'
    # 컨텍스트 객체 이름을 기본값(object_list)와 다르게 지정했지만,
    # 기본값(object_list)도 여전히 사용 가능함
    context_object_name = 'posts'
    paginate_by = 2  # 페이지 당 2 개 객체를 처리하도록 지정

# DetailView를 상속받아서 PostDV 작성
# 기본키 대신 slug를 전달 받고, 나머지 속성은 기본값 사용
# slug는 URLconf가 전달해줌(3.1.4 URL 설계 항 참고)
class PostDV(DetailView) :
    model = Post

# 모든 아카이브 클래스에서 기준 날짜(date_filed) 속성을 modify_date로 지정

# ArchiveIndexView를 상속받아서 PostAV 작성
class PostAV(ArchiveIndexView) :
    model = Post
    date_field = 'modify_date'

# YearArchiveView를 상속받아서 PostYAV 작성
class PostYAV(YearArchiveView) :
    model = Post
    date_field = 'modify_date'
    make_object_list = True    # 기본값은 False이지만,
    # object_list 컨텍스트 변수를 생성해서 템플릿에 전달하도록 지시
    # URLconf에서 추출한 연도 값을 전달받아서 object_list를 구성하고
    # 이를 템플릿에 전달함

# MonthArchiveView를 상속받아서 PostMAV 작성
class PostMAV(MonthArchiveView) :
    model = Post
    date_field = 'modify_date'
    # URLconf에서 추출한 연도 및 월 값을 전달받아서 object_list를 구성하고
    # 이를 템플릿에 전달함

# DayArchiveView를 상속받아서 PostDAV 작성
class PostDAV(DayArchiveView) :
    model = Post
    date_field = 'modify_date'
    # URLconf에서 추출한 연도, 월, 일 값을 전달받아서 object_list를 구성하고
    # 이를 템플릿에 전달함

# TodayArchiveView를 상속받아서 PostTAV 작성
class PostTAV(TodayArchiveView) :
    model = Post
    date_field = 'modify_date'
    # URLconf에서 지정한 당일(today)에 해당하는 object_list를 구성하고
    # 이를 템플릿에 전달함  

blog/templates/blog/post_all.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>장고 블로그</title>
</head>
<body>
    <!--특별한 HTML 태그 지정이 없으면 장고가 <body> </body> 영역으로 간주함-->
    <h1>Blog List</h1>

    <!--blog.views.PostLV.context_object_name='posts'라고
    기본값 object_list 대신 정의했지만, object_list 역시 사용 가능함-->
    {% for post in posts %}
        <h2>
            <!--href='blog/post/django-example/'과 같은 슬러그 형태로 링크 처리하되,
             blog.models.Post.get_absolute_url() 함수  또는
            % url url_name pk %}로 링크 처리-->
            <a href='{{ post.get_absolute_url }}'>
            <!--위 a 요소와 아래 a 요소는 동일한 코드이지만,
            위는 url 패턴을 간접 태그 인자로 사용하지만,
            아래는 url 패턴을 직접 태그 인자로 사용함 -->
            <!--<a href="{% url 'blog:post_detail' post.slug %}}">-->
                {{ post.title }}
            </a>
        </h2>
        <!--post.modify_date를 date:"N d, Y" 형식으로 출력 (예: July 05, 2015) cf. http://oddly.tistory.com/64-->
        {{ post.modify_date|date:"N d, Y" }}
        <p>{{ post.description }}</p>
    {% endfor %}

    <br/>

    <!--이전/현재/다음 페이지 이동 -->
    <div> <!--div 요소는 블록 요소-->
        <span>  <!--span 요소는 인라인 요소-->
            <!--page_obj는 장고 Page 객체가 들어있는 컨텍스트 변수이며
            has_previous, has_next, previous_page_number, next_page_number,
            number, pagenator.num_pages 속성을 가짐-->
            {% if page_obj.has_previous %}
                <!--링크 형식 href="?page= page_obj.previous_page_number "에 주목-->
                <a href="?page={{ page_obj.previous_page_number }}">이전 페이지</a>
            {% endif %}

            페이지 {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}

            {% if page_obj.has_next %}
                <!--링크 형식 href="?page= page_obj.previous_page_number "에 주목-->
                <a href="?page={{ page_obj.next_page_number }}">다음 페이지</a>
            {% endif %}
        </span>
    </div>
</body>
</html>

blog/templates/blog/post_archive.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>장고 블로그3</title>
</head>
<body>
    <!--% now % 템플릿 태그는 현재 일시를 "N d, Y" 형식(July 18, 2015)으로 출력  -->
    <h1>{% now "N d, Y" %}까지의 게시글 모음</h1>
    <ul>
        <!--date_list 컨텍스트 변수는 DateQuerySet 객체 리스트를 담고 있으며, 여기에는-->
        <!--QuerySet에서 날짜 정보만을 추출해서 datetime.date 유형의 객체로 저장함 -->
        {% for date in date_list %}
            <!--연도 리스트를 inline 방식으로 출력-->
            <li style="display: inline;">
                <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">
                    {{ date|date:"Y" }} 년
                </a>
            </li>
        {% endfor %}
    </ul>
    <br/>
    <div>
        <ul>
            <!--기본 컨텍스트 변수로 object_list 및 lates 모두 가능함-->
            {% for post in object_list %}
                <li>
                    <!-- 순서 없는 리스트로 게시글 수정일과 제목을 공백 3개로 구분하여 출력 -->
                    {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                    <a href="{{ post.get_absolute_url }}">
                        <strong>{{ post.title }}</strong>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

blog/templates/blog/post_archive_day.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ day|date:"Y년 b월 d일"}} 게시글 모음</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>
            {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

blog/templates/blog/post_archive_month.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ month|date:"Y년 m월" }} 게시글 모음</h1>

    <div>
        <ul>
            {% for post in object_list %}
            <li>
                {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}">
                    <strong>{{ post.title }}</strong>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

blog/templates/blog/post_archive_year.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ year|date:"Y" }}년 게시글 모음</h1>

    <ul>
        <!--date_list 컨텍스트 변수는 DateQuerySet 객체 리스트를 담고 있으며, -->
        <!--여기에는 QuerySet에서 날짜 정보만을 추출해서 datetime.date 유형의 객체로 저장함 -->
        {% for date in date_list %}
        <li style="display: inline">
            <!--'blog:post_month_archive' url에 링크 연결하되, 2015(년) 및 7(월) 형식으로 매개변수를 전달-->
            <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">
                <!--월 제목을 "F" 형태(예: July)로 출력 -->
                {{ date|date:"F" }}
            </a>
        </li>
        {% endfor %}
    </ul>
    <br/>

    게시글 리스트 출력 부분은 post_archive.html과 동일한 방식
    <div>
        <ul>
            <!--기본 컨텍스트 변수로 object_list 및 lates 모두 가능함-->
            <!--latest는 ArchiveIndexView에서만 정의된 변수이므로 여기서는 사용 불가-->
            {% for post in object_list %}
            <li>
                {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp
                <a href="{{ post.get_absolute_url }}">
                    <strong>{{ post.title }}</strong>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>장고 블로그2</title>
</head>
<body>
<!--특별한 HTML 태그 지정이 없으면 장고가 <body> </body> 영역으로 간주함-->
<!--아래에서 object 객체는 PostDV 클래스 형 뷰에서
컨텍스트 변수로 넘겨주는 Post 클래스의 특정 객체-->

<!--object.title을 H2 요소로 출력 -->
<h2>{{ object.title }}</h2>

    <p class="other_posts">
        <!--object.get_previous_by_modify_date 함수는 modify_date 기준으로 이전 객체를 반환-->
        {% if object.get_previous_by_modify_date %}
            <!--blog.Post.get_previous_post 함수는 이전 객체를 반환 -->
            <!--get_absolute_url 함수는 /blog/post/slug단어 형태의 URL 패턴을 반환-->
            <!--'&laquo;'는 HTML 특수 문자 '<<'를 의미함-->
            <a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post">
                &laquo;--{{ object.get_previous_post }}
            </a>
        {% endif %}

        {% if object.get_next_by_modify_date %}
            |
            <!--blog.Post.get_next_post 함수는 다음 객체를 반환 -->
            <!--get_absolute_url 함수는 /blog/post/slug단어 형태의 URL 패턴을 반환-->
            <!--'&raquo;'는 HTML 특수 문자 '>>'를 의미함-->
            <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post">
                {{ object.get_next_post }}--&raquo;
            </a>
        {% endif %}
    </p>
    <!--object.modify_date를 파이프(|)를 통하여 date:"j F Y" 형식으로 출력-->
    <p class="date">{{ object.modify_date|date:"j F Y" }}</p>
    <br/>

    <div class="body">
        <!--object.content를 파이프(|)를 통하여 linebreaks 탬플릿 필터로 처리하여
         개행문자'\n'를 인식하도록 조치함-->
        {{ object.content|linebreaks }}
    </div>
</body>
</html>